### ISSUE TITLE
Feedback on page SDL_CreateCursor

### ISSUE THREAD

**Issue by marijnvdwerf** [libsdl-org/sdlwiki#100]
White and transparent are documented as requiring the same values, but transparency is actually achieved by setting mask to 0 instead. 

```
data=0, mask=1: white
data=0, mask=1: transparent
             ^
             Should be 0
```

**Comment by icculus** [comment]
Fixed in 5b3b41b0e22e3668802855cdbf2d79d006c2f74f, thanks!
