### ISSUE TITLE
Feedback on page SDL_GetMouseState

### ISSUE THREAD

**Issue by JoeStrout** [libsdl-org/sdlwiki#116]
Is this code sample correct?  It's getting buttons into local variable `buttons`, but then not actually using in the button check — instead just invoking the SDL_BUTTON macro as if it's a function (which it does not appear to be).

**Comment by slouken** [comment]
Yup, that wasn't correct. It's fixed in https://github.com/libsdl-org/sdlwiki/commit/4cc0882f1a0f1f30916f65922b501165f479f579 and improved in https://github.com/libsdl-org/sdlwiki/commit/0528676f5aef169542f090ee438bf85b8c7dfd85.

Thanks!
