### ISSUE TITLE
Feedback on page Tutorials

### ISSUE THREAD

**Issue by dandago** [libsdl-org/sdlwiki#118]
Just wanted to suggest adding a link to my [SDL2 tutorials](https://gigi.nullneuron.net/gigilabs/writing/sdl2-tutorials/), which many have found helpful over the years. Sorry for the shameless plug, but perhaps some people might find this useful. Thanks.

**Comment by icculus** [comment]
This was added in f77ac22fcbb176711f7b021ff4ec6ac5c6b6e801 (after much delay...sorry...)
