### ISSUE TITLE
Document SDL_EventFilter and SDL_ThreadFunction

### ISSUE THREAD

**Issue by Quipyowert2** [libsdl-org/sdlwiki#152]
SDL_EventFilter and SDL_ThreadFunction pages are missing. There are code examples of how to use these function pointers on the [`SDL_SetEventFilter`](https://wiki.libsdl.org/SDL_SetEventFilter) and [`SDL_CreateThread`](https://wiki.libsdl.org/SDL_CreateThread) pages. The pages link to the pages for the two function pointers but the pages for the function pointers themselves don't exist. I can easily find the `typedef`s for these function pointers through grepping the SDL2 headers but it would be nice to have some documentation of them on the wiki.

**Comment by dustdfg** [comment]
Hi @icculus! This issue is solved now
