### ISSUE TITLE
Feedback on page SDL_assert_data

### ISSUE THREAD

**Issue by ghost** [libsdl-org/sdlwiki#160]
`SDL_assert_data` is deprecated, and thus its wiki page should likely be renamed to the updated `SDL_AssertData`. This looks to have already been done for the corresponding structure `SDL_AssertState`.

I would have edited the page, but am unsure how to go about moving/renaming the page itself from https://wiki.libsdl.org/SDL_assert_data. What is the best way to go about this? Is there any way to do this through the web UI, or is it only allowed through more traditional git methods?

**Comment by icculus** [comment]
This got updated when wikiheaders started bridging structs to the wiki.
