### ISSUE TITLE
Wiki header logo can be a link to homepage?

### ISSUE THREAD

**Issue by theweirdn8** [libsdl-org/sdlwiki#190]
Hello,

Unsure if this is OCD, but I will like to be able to click on the SDL wiki tile on top and go to the homepage. Can you add this?

**Comment by icculus** [comment]
Your wish is my command!  https://github.com/icculus/ghwikipp/commit/b42645c2beafc86cc3f3108554c061b91b042e90

**Comment by theweirdn8** [comment]
My hero! :-)
