### ISSUE TITLE
Feedback on page FrontPage

### ISSUE THREAD

**Issue by striderssoftware** [libsdl-org/sdlwiki#2]
Where is the search box?

**Comment by Erquint** [comment]
Can't search on this new very broken site.
No `oldwiki` subdomain.
Obviously can't search on the WayBack machine snapshots of the old wiki.
Can't even really search here on GitHub.
No search whatsoever. This is painful.

**Comment by icculus** [comment]
There's a "search" link at the bottom of the page.

**Comment by icculus** [comment]
(also: the raw wiki text can be cloned with git, and you can download a .zip of the HTML from a link at the bottom of the page, if you have other tools you want to use with it.)

**Comment by Erquint** [comment]
Was it there just a minute ago? Could swear I `[Ctrl]+[F]` searched for `search` on the page and couldn't find it.

Wish devdocks.io would pick it up…

**Comment by icculus** [comment]
> Anyway, scales uncomfortably and overall hardly readable on my screen

the CSS could definitely use some work. I basically clamped it so people with obscenely large monitors can get some wordwrap instead of a long horizontal line of text, but I'm not committed to any of it, if there are obvious improvements to be made.

**Comment by Erquint** [comment]
I'm mostly an edge-case with my tiny monitor…
Am I going to have to host MediaWiki locally for this now?
Are there any better local options?

**Comment by icculus** [comment]
>  Am I going to have to host MediaWiki locally for this now?

I don't think so...?  Currently all of the pages are MediaWiki format, but they can optionally be Markdown instead, and might be in the future.

> Here's a nugget

Yeah, making an offline archive was one of the goal of this work; the "offline html" link in the footer gives you a .zip of the whole wiki as HTML files, generated once a night.

**Comment by Erquint** [comment]
Yeah, I can see you're using `pandoc` there.
Best worst-case scenario if pages were all actually intact — I guess I could `pandoc` them to markdown and load up in a code-editor project as reference.
Hosting mediawiki  as well as reading it or HTML raw is a gigantic pain.

Currently, though, some crucial pages are [broken](./7).

**Comment by icculus** [comment]
The CSS is (in my opinion, at least) much better now, and there's a separate issue open suggesting we move the search link to the top of the page, which probably solves the specific issue reported here, so I'm going to close this one.
