### ISSUE TITLE
Where's the old website..?

### ISSUE THREAD

**Issue by dbechrd** [libsdl-org/sdlwiki#213]
Why did you delete all of the documentation and replace it with a wiki that's missing half of the docs? This makes literally no sense.

E.g.
Old: https://web.archive.org/web/20190322092347/http://wiki.libsdl.org/SDL_CreateTexture
New: https://wiki.libsdl.org/SDL_CreateTexture

The new page is missing all of the format an access enumeration values. I'm sure there are many more examples. Don't follow MSDN's example and launch your new docs page before it's even at parity with the old one. This is extremely stupid and irresponsible.

**Comment by slouken** [comment]
You can click the link for the format and access parameters to see the available values. We've also moved the remarks above the code example section so they're easier to read.

**Comment by dbechrd** [comment]
Yeah sorry, I was just really frustrated when I wrote this. I appreciate the effort in trying to make the docs website newer or whatever, but I've been using SDL for 15 years and when the docs just randomly change to completely different format, different colorscheme, etc. with no way to access the old website, it's suuuuuuuper frustrating. It's like when the grocery store moves which shelf everything is on. It doesn't really help anyone, it just makes everyone have to relearn their habits. :/

**Comment by dbechrd** [comment]
Ah, didn't realize the goal was full auto-gen. Seems noble enough. I very much appreciate your patience in responding to angry github issue comments from someone who has otherwise contributed very little to the project. SDL is an amazing, trend-setting community library that adds great value to our industry, so thanks for your time and contribution, and for interpreting my comments as passion, rather than hate.

**Comment by slouken** [comment]
You're welcome! :)
