### ISSUE TITLE
Feedback on page CategoryVulkan

### ISSUE THREAD

**Issue by crkellen** [libsdl-org/sdlwiki#22]
On Firefox Beta, 88.0b9, could be someone on my end, an addon or something, but doesn't seem immediately apparent what if so.
Text goes off screen, no word wrap.

![image](https://user-images.githubusercontent.com/6870231/114326306-c35b3200-9af9-11eb-8294-5fee270baaff.png)

**Comment by icculus** [comment]
Fixed in https://github.com/libsdl-org/sdlwiki/commit/00f55319335d3a0c492d9527b34ab6bf93467f0d, thanks!
