### ISSUE TITLE
Not able to edit specific page

### ISSUE THREAD

**Issue by pedro-w** [libsdl-org/sdlwiki#229]
I was trying to edit https://wiki.libsdl.org/CategoryLog and was unable to, because the preview tab just shows an empty page. Before I edit, it's fine, but even making a trivial change (e.g. inserting a space between two words) gives the blank preview.
I can edit other pages fine.
Using Firefox 100 / Mac

**Comment by madebr** [comment]
Perhaps similar, but when visiting https://wiki.libsdl.org/CategoryLog, I get `No such page 'CategoryLog' yet.`.

**Comment by icculus** [comment]
The fix in #243 is merged, so I'm going to close this, but I'll open an issue in ghwikipp where it'll refuse to accept an edit if pandoc throws an error.

(this particular error was a legacy from our import from MoinMoin, as far as I'm aware, and the preview view will be blank if such an edit were attempted, but that whole thing could be more robust...both in refusing to accept the edit and in the preview showing a "this edit has an error!" message.)
