### ISSUE TITLE
Grep for '<<include'

### ISSUE THREAD

**Issue by icculus** [libsdl-org/sdlwiki#233]
Rather than stumble upon these forever, someone should just clean out all the '<<include' strings that did magic things in MoinMoin.

We've actually gotten a lot of them. Here's a search of what remains.

https://wiki.libsdl.org/wiki/search?q=%3C%3Cinclude

**Comment by madebr** [comment]
What is the correct fix for this? Copy and paste?
Is https://wiki.libsdl.org/SGWikiBasics#includes outdated?

**Comment by icculus** [comment]
Any of the "SG" pages ("Style Guide") are almost certainly out of date at this point; they were written for the MoinMoin wiki right during the transition between SDL 1.2 and SDL 2.

I haven't looked through them, but they'd likely need updating for both MediaWiki syntax and just general truths that have changed in the last decade+.

**Comment by icculus** [comment]
Also, at some point ghwikipp started dropping the `?q=search_terms` from that link, so that's a separate bug.  :(

**Comment by icculus** [comment]
As to the question: the correct answer varies.

- For extremely small things that never change: copy/paste.
- For things that make sense to live on a separate page (or be part of an existing page), link to them and don't have it inline on every page.
- For many other things: delete the "include" macro stuff. It's often not worth listing out the things we're listing out between pages like this.

But all of that's absolutely a decision that needs to be made per-page.

**Comment by icculus** [comment]
So all the MoinMoin `<<` things are gone from the SDL3 wiki.

The Style Guide stuff is now deleted from SDL2's wiki (it already was for SDL3), but a handful of related things that do this still remain there...most of them will evaporate when we fix up the Category stuff in wikiheaders, I think.
