### ISSUE TITLE
Feedback on page SourceCode

### ISSUE THREAD

**Issue by IAbstract** [libsdl-org/sdlwiki#235]
On the [wiki][1], the link to the `git` (2.0) is old or non-existent and does not match the `github` link.
![SDL github link](https://user-images.githubusercontent.com/987431/171131410-7b1b8b97-fc70-4d54-83a4-30838ab43202.png)

[1]: https://wiki.libsdl.org/SourceCode

**Comment by icculus** [comment]
The "Git" link is to where to download the Git client. It's not meant to be the same link as listed below for cloning SDL.
