### ISSUE TITLE
Feedback on page SDL_CreateRenderer

### ISSUE THREAD

**Issue by zchrissirhcz** [libsdl-org/sdlwiki#236]
The example code calls `SDL_LoadBMP()`, and seem missing a corresponding `SDL_FreeSurface()` call.
From https://wiki.libsdl.org/SDL_LoadBMP page, it says `SDL_FreeSurface()` is required, otherwise will cause memory leak.

**Comment by madebr** [comment]
I think this is already done.

`SDL_FreeSurface(bitmapSurface)` is there.

https://github.com/libsdl-org/sdlwiki/blob/7554f5546fb89879b335463bd6fbe50da9082115/SDL_CreateRenderer.mediawiki?plain=1#L56
