### ISSUE TITLE
Will the build bot be revived?

### ISSUE THREAD

**Issue by madebr** [libsdl-org/sdlwiki#242]
The installation page talks about a build bot providing binaries,
but the latest builds date September 2021 (~10 months ago).
https://buildbot.libsdl.org/sdl-builds/

https://github.com/libsdl-org/sdlwiki/blob/7554f5546fb89879b335463bd6fbe50da9082115/Installation.mediawiki?plain=1#L77

https://github.com/libsdl-org/sdlwiki/blob/7554f5546fb89879b335463bd6fbe50da9082115/Installation.mediawiki?plain=1#L146

https://github.com/libsdl-org/sdlwiki/blob/7554f5546fb89879b335463bd6fbe50da9082115/Installation.mediawiki?plain=1#L158-L159

and more

**Comment by icculus** [comment]
We're moving over to GitHub Actions. Buildbot is already gone, and many of the existing builds are already running per-push on Actions, and there are ongoing goals to replicate most of the functionality we lost from Buildbot there (static analysis, per-build artifacts uploaded somewhere).

Some platforms, like QNX, are not migrating over to Actions, those are being dropped.

That work is being tracked over here: https://github.com/libsdl-org/SDL/issues/4758

**Comment by icculus** [comment]
(Also, buildbot.libsdl.org will become a static page eventually...the server is still running, but the machine with all the workers is unplugged and has been repurposed...I have a full backup of all the worker virtual machines, though.)

**Comment by icculus** [comment]
https://buildbot.libsdl.org has been redirecting to https://github.com/libsdl-org/SDL/actions for awhile now, and I've since removed the references to buildbot from the wiki.
