### ISSUE TITLE
Feedback on page SDL_BlitScaled

### ISSUE THREAD

**Issue by dlqqq** [libsdl-org/sdlwiki#252]
The page for [SDL_BlitSurface](https://wiki.libsdl.org/SDL_BlitSurface) includes the following note in the "Remarks" section on behavior if `dstrect == NULL`:

> Only the position is used in the dstrect (the width and height are ignored)...
> If dstrect is NULL, then the destination position (upper left corner) is (0, 0).

However, there's no corresponding remark for the SDL_BlitScaled documentation on what happens if `dstrect == NULL`. It looks like it behaves "as expected" where `dstrect` defaults to:

```
dstrect.x = 0;
dstrect.y = 0;
dstrect.w = dst->w;
dstrect.h = dst->h;
```

There should be a remark about this in the documentation.

**Comment by slouken** [comment]
This is actually called out in the description of the dstrect parameter:
"the [SDL_Rect](https://wiki.libsdl.org/SDL_Rect) structure representing the rectangle that is copied into, or NULL to copy into the entire surface"
