### ISSUE TITLE
All category pages display special command

### ISSUE THREAD

**Issue by dustdfg** [libsdl-org/sdlwiki#254]
Hello!

All the category pages display lines similar to the following:
`<<FullSearchCached(category:CategoryDefine -SGHints)>>`

**Comment by dustdfg** [comment]
![Screenshot from 2022-08-20 21-21-38](https://user-images.githubusercontent.com/97330399/185761263-6b921fc1-93b8-4f6d-87a5-5b2c77eb0cad.png)

**Comment by dustdfg** [comment]
I also found  `<<MailTo(ANTI SPAM wiki AT libsdl DOT org)>>` at https://wiki.libsdl.org/Contributing. Maybe it is a problem with all special commands

**Comment by dustdfg** [comment]
I tried to understand where problem is and found that ghwikipp not uses MoinMoin now. I am not sure but it seems to me that it uses pandoc and [build_categories.php](https://github.com/libsdl-org/ghwikipp/blob/main/build_categories.php) script that doesn't support separation by enum, functions and structs.

1. To solve the problem with displaying special commands of MoinMoin we just need to delete them. Am I right?
2. I can propose to extend the [build_categories.php](https://github.com/libsdl-org/ghwikipp/blob/main/build_categories.php) script and syntax of `<!-- BEGIN CATEGORY LIST -->` to separate enums, structs and functions. What do you think about it?

**Comment by slouken** [comment]
Yes, at this point we can just delete the MoinMoin commands and replace them with equivalent mediawiki syntax.

> I can propose to extend the [build_categories.php](https://github.com/libsdl-org/ghwikipp/blob/main/build_categories.php) script and syntax of  to separate enums, structs and functions. What do you think about it?

That sounds like a good idea, what do you think @icculus?

**Comment by Lucretia** [comment]
The audio category doesn't render properly.

**Comment by icculus** [comment]
This is resolved now! (and the category pages have functions/enums/macros/structs/etc split out, too)
