### ISSUE TITLE
Table style conventions 2 or 3 column

### ISSUE THREAD

**Issue by dustdfg** [libsdl-org/sdlwiki#262]
Hello!

I noted that for Struct pages ([example](https://wiki.libsdl.org/SDL_FRect)) wiki uses 3 column tables as (type,name,description) but for Function pages ([example](https://wiki.libsdl.org/SDL_IntersectFRect)) wiki uses 2 column tables as (name, description that sometimes points type). I think that it could be better to use 3 column tables for Function pages but I am afraid that it is a convention so I didn't try to change it. What do you think about? (Can/Should) use 3 column tables for Function pages?

**Comment by icculus** [comment]
These get generated by a script now, and just show the relevant C structure inline. I think it looks pretty good.  :)

(The SDL_FRect example you pointed to doesn't have any comments in it, but other structs do, and those transfer over to the wiki from the headers, too.)
