### ISSUE TITLE
Feedback on page CategoryEvents

### ISSUE THREAD

**Issue by dustdfg** [libsdl-org/sdlwiki#263]
I tried to fix separation of different entity types https://github.com/libsdl-org/sdlwiki/commit/f00ce29881e3bdc5bb3752554fe3c48fe8750901 using syntax described in MoinMoin [documentation](http://moinmo.in/HelpOnCategories). It dosn't work and problem is still present. I also want to say that it also have problem described in https://github.com/libsdl-org/sdlwiki/issues/254

**Comment by icculus** [comment]
We replaced all the Category* pages this morning, so this should be resolved now!
