### ISSUE TITLE
SDL(Scan/Key)codeLookup broken links / missing pages?

### ISSUE THREAD

**Issue by past-due** [libsdl-org/sdlwiki#27]
https://wiki.libsdl.org/SDL_Scancode

Links to:
https://wiki.libsdl.org/SDLScancodeLookup
https://wiki.libsdl.org/SDLKeycodeLookup

But those pages appear to not exist yet / didn't make the move?

**Comment by weslord** [comment]
These links work now!

KeycodeLookup was created in 73a25013e261af2f426039882b0b221e64013925

ScancodeLookup page generation fixed in eda9d2a0e6cbbc8031cc6341ac8ecca8d44eabc2 - although someone may need to verify that the table is complete and correct.

**Comment by slouken** [comment]
Great, thanks!
