### ISSUE TITLE
Feedback on page SDL_JoystickIsHaptic

### ISSUE THREAD

**Issue by theMealena** [libsdl-org/sdlwiki#296]
hi

- Win 10 + Xinput Xbox360 controllers are not seen as haptic, which was ok on SDL2.0.7
- using SDL_Joystick and not SDL_Gamepad.
- tested with : 

`
int TEST_haptic(void)
 {

    if (SDL_Init(SDL_INIT_JOYSTICK | SDL_INIT_HAPTIC))
    {
        printf("Cannot init: %s\n", SDL_GetError());
        return 1;
    }

    int num = SDL_NumJoysticks();
    printf("found %d joystick\n", num);
    int i;

    for (i = 0; i < num; i++)
    {
        SDL_Joystick* joy = SDL_JoystickOpen(i);
        if (!SDL_JoystickIsHaptic(joy))
        {
         printf("Joystick is not haptic!\n");
         continue;
        }

        SDL_Haptic* haptic = SDL_HapticOpenFromJoystick(joy);

        if (SDL_HapticRumbleInit(haptic))
        {
            printf("Cannot init haptic: %s\n", SDL_GetError());
            return 1;
        }
    }

        SDL_HapticRumblePlay(haptic, 1.0, 2000);

        SDL_Delay(3000);

        SDL_HapticClose(haptic);
        SDL_JoystickClose(joy);
    }

    return 0;}`

**Comment by slouken** [comment]
The haptic system is deprecated and no longer works for gamepads. You should use `SDL_GameControllerRumble()` instead.
