### ISSUE TITLE
Feedback on page SDL2/SDL_Vulkan_GetVkInstanceProcAddr

### ISSUE THREAD

**Issue by puzzlepaint** [libsdl-org/sdlwiki#327]
This page appears to have an inconsistency:

In the URL, it is written as "SDL_Vulkan_GetVkInstanceProcAddr", but this function does not seem to exist. Instead, there is "SDL_Vulkan_GetVkGetInstanceProcAddr" (with an additional "Get"), as described on the actual page content.

In addition, there is a separate page https://wiki.libsdl.org/SDL2/SDL_Vulkan_GetVkGetInstanceProcAddr that has the correct spelling in its URL and describes the same function, with slightly different page content.

Note that the page https://wiki.libsdl.org/SDL2/SDL_Vulkan_LoadLibrary links to the URL with the wrong spelling under "Related Functions".

**Comment by icculus** [comment]
Yeah, https://wiki.libsdl.org/SDL2/SDL_Vulkan_GetVkGetInstanceProcAddr is the correct page, I've deleted the other. It was a typo in the docs that caused a duplicate.

The SDL_Vulkan_LoadLibrary page was fixed at some point, too.
