### ISSUE TITLE
400 Bad Request on SDL_Image, SDL_Mixer and SDL_ttf

### ISSUE THREAD

**Issue by ghost** [libsdl-org/sdlwiki#355]
The pages for  SDL_Image, SDL_Mixer, and SDL_ttf all return a _400 Bad Request_ page! It's been this way for weeks!

**Comment by slouken** [comment]
Ryan, can you take a look at this?

**Comment by icculus** [comment]
Oh, it's working for

https://wiki.libsdl.org/SDL2_mixer

But not

https://wiki.libsdl.org/SDL_mixer

I'll figure out why it's not redirecting properly.

**Comment by icculus** [comment]
This got fixed a long time ago but the issue was never closed (sorry!). Closing now.
