### ISSUE TITLE
Feedback on page SDL3/Tutorials-AudioStream

### ISSUE THREAD

**Issue by sbmoonbeam** [libsdl-org/sdlwiki#379]
The types are now prefixed with SDL_  , e.g SDL_AUDIO_S16  , so your code that just changes the function name from the SDL2 demo won't compile.

**Comment by icculus** [comment]
Fixed in 3f1bb54b1b1703aab700b3c1272afaac2ce60ba3, thanks!

**Comment by icculus** [comment]
(This is at https://wiki.libsdl.org/SDL3/Tutorials/AudioStream now)
