### ISSUE TITLE
Feedback on page SDL2/FAQUsingSDL: ftp://ptah.lnf.kth.se/pub/misc/sdl-env-vars link broken

### ISSUE THREAD

**Issue by qwertychouskie** [libsdl-org/sdlwiki#410]
ftp://ptah.lnf.kth.se/pub/misc/sdl-env-vars no longer exists from what I can tell.

**Comment by icculus** [comment]
I changed this to link to SDL's internal list, now. I assume the old link was for SDL 1.2 anyhow.
