### ISSUE TITLE
Page on SDL2/README/dynapi lacks info on how to disable it

### ISSUE THREAD

**Issue by ell1e** [libsdl-org/sdlwiki#429]
The wiki page on SDL2/README/dynapi lacks info on how to disable it when compiling SDL2 from source: https://sdl-mirror.readthedocs.io/en/latest/README-dynapi.html and there's nothing that jumps out in `./configure --help` either. It would be nice of both places listed an obvious way to do that. (Might be useful e.g. when shipping with a bleeding edge SDL2 with new bugfixes or custom patches and wanting to prevent Steam from downgrading it.)

**Comment by slouken** [comment]
We strongly recommend not disabling that feature. Steam doesn't override your SDL library and won't except in the event that your game doesn't work for customers.

**Comment by ell1e** [comment]
Ah, very interesting, so it's not always replaced as part of the Linux runtime with some custom variant? Somehow I assumed that, useful to know it's not! I guess it's kind of answered in the last paragraph but maybe it could be more explicit:

Like, some "How to disable this?" bold question followed by like "Since this should only ever used by people trying to make your program run and not as a standard to upgrade around SDL2 apps without need risking breakage, you really shouldn't. If you somehow still want to, dig into the dynamic API's code file and it should be obvious enough." or something like that? Just to make it less easy to miss.
