### ISSUE TITLE
Feedback on page SDL2/SDL_SysWMinfo

### ISSUE THREAD

**Issue by u-an-i** [libsdl-org/sdlwiki#433]
this page appears to contain garbled formatting.  
  
Also the substructure is not provided in full as of SDL 2.28.4, eg. the windows Windows window handle is in `info.win.window`, so it has to be accessed by `info.info.win.window` given a `SDL_SysWMinfo info`.

**Comment by icculus** [comment]
This was fixed when we moved more stuff over to the wiki/header bridge, recently.
