### ISSUE TITLE
Feedback on page SDL2/Installation

### ISSUE THREAD

**Issue by rogermilne** [libsdl-org/sdlwiki#439]
The "Static Linking" paragraph on this page is very confusing to me, because it uses the words "this" and "that".  Is "this" referring to static linking, or to compiling code directly into the app?  Likewise, what is "that" referring to?  I'd appreciate it really being spelled out for me please :-)

**Comment by icculus** [comment]
I've clarified the wording a little in 18134b782c546be9b710460d3c0b029d0378dd92, thanks!
