### ISSUE TITLE
Feedback on page SDL3/SDL_GetWindowWMInfo

### ISSUE THREAD

**Issue by c-smile** [libsdl-org/sdlwiki#443]
this is incorrect:
```
SDL_VERSION(&info.version); 
```
`SDL_VERSION` expects a `SDL_version` struct to initialize but `info.version` is an int.

**Comment by slouken** [comment]
This function is actually gone in SDL3.

@icculus, is there any way to automate new/removed function synchronization between the Wiki and headers?

**Comment by c-smile** [comment]
If not SDL_GetWindowWMInfo then how to get platform HWND?

**Comment by slouken** [comment]
If you're ever curious about API changes in SDL3, you can look them up in README-migration.md:
https://github.com/libsdl-org/SDL/blob/main/docs/README-migration.md#sdl_syswmh

**Comment by icculus** [comment]
I never wrote the code to remove pages because it's risky and before SDL3 we never removed anything.  :)

We could probably just delete everything, run the bridge, and see what pages git sees are still missing afterwards...then we just remove+commit what's appropriate.

**Comment by slouken** [comment]
Yeah, that sounds like a good plan.

**Comment by icculus** [comment]
This (and all the other no-longer-existing function pages) are gone now.

And, in case you missed it, you can get the HWND with the SDL_PROP_WINDOW_WIN32_HWND_POINTER property with the object returned by [SDL_GetWindowProperties](https://wiki.libsdl.org/SDL3/SDL_GetWindowProperties).
