### ISSUE TITLE
Feedback on page SDL2/Installation

### ISSUE THREAD

**Issue by Zectbumo** [libsdl-org/sdlwiki#451]
I want to download the prebuilt dll for windows 10 but the link that is provided doesn't seem to work and doesn't make sense
https://buildbot.libsdl.org/sdl-builds/sdl-visualstudio/?C=M;O=D

**Comment by icculus** [comment]
Oh, yeah, we used to publish builds for each commit for testing purposes, but now I think we only do it for official releases. I'll fix that.

Releases are at https://github.com/libsdl-org/SDL/releases
