### ISSUE TITLE
Insufficient information on SDL_RendererFlags and their interoperability.

### ISSUE THREAD

**Issue by iloveclang** [libsdl-org/sdlwiki#458]
Specifically, SDL_RENDERER_SOFTWARE and SDL_RENDERER_ACCELERATED. It is difficult to deduce from the source code how the SOFTWARE flag affects the program, as it is both an active override to ACCELERATED drawing in SDL_RenderGeometryRaw(), and a supposed fallback when an accelerated renderer couldn't be found. No one on the internet knows the answer to this, but I think there should be one, given that these are basic settings for a core function.

PROPOSED SOLUTION:  
 - explain better what SDL_RENDERER_SOFTWARE does, how it interacts with SDL_RENDERER_ACCELERATED, and what happens in the 4 possible combimations of these flags being ON/OFF

**Comment by icculus** [comment]
A better question is why we have both, when SOFTWARE and ACCELERATED are mutually exclusive.

**Comment by slouken** [comment]
Because there is a third state "give me either one, I don't care"

**Comment by iloveclang** [comment]
So setting no flags will try to first get ACCELERATED, and then SOFTWARE?

Setting ACCELERATED AND SOFTWARE will prioritize ACCELERATED in the same way, or will it be a gamble?

Setting one, but not the other will give you that one.

Can you confirm or deny that this is how it works? Does behaviour depend on the drivers?

**Comment by slouken** [comment]
In SDL2, setting one flag will guarantee that kind of renderer. Setting both flags or no flags will try accelerated first and fall back to software.

**Comment by sridenour** [comment]
@slouken Setting both flags fails in SDL2, as it can't find a renderer that supports both `SDL_RENDERER_ACCELERATED` *and* `SDL_RENDERER_SOFTWARE`.

```
uint32_t renderFlags = SDL_RENDERER_ACCELERATED | SDL_RENDERER_SOFTWARE;
SDL_Renderer *renderer = SDL_CreateRenderer(window, -1, renderFlags);
```
fails, with `SDL_GetError()` reporting: `Couldn't find matching render driver`

**Comment by slouken** [comment]
Ah, okay, thanks for clarifying!
