### ISSUE TITLE
CreateRGBSurface and indexed images

### ISSUE THREAD

**Issue by zlago** [libsdl-org/sdlwiki#477]
from my observations, when creating indexed color images (bit depth 8 or less), `SDL_CreateRGBSurface` will:
- fail if any of the 3 color masks is not zero
- ignore the alpha mask
	* which means setting it wont cause it to fail
	* but also that it will set the blending mode as if Amask was 0

is this a bug with SDL2.30, or intentional behaviour that has not been documented on the wiki?

**Comment by slouken** [comment]
I don't know if it's intentional behavior, but has been that way for so long that it would probably introduce issues if you tried to change it. SDL_CreateRGBSurface() is gone in SDL3, so let me know if there are any improvements we can make there before the ABI is locked down.
