### ISSUE TITLE
Feedback on page SDL_GetRenderDrawColor

### ISSUE THREAD

**Issue by homosapien97** [libsdl-org/sdlwiki#48]
Low priority:
The section of the page with the _CategoryAPI, CategoryRender_ links does not have a header. It seems like if this is a standard part of a page describing a function, it could be given the header "Categories" on every page. Otherwise, without a header, editors can only guess as to what is supposed to be in that section by looking a what's already there.

**Comment by icculus** [comment]
This got fixed at some point.
