### ISSUE TITLE
Footer and header text/links are too tiny

### ISSUE THREAD

**Issue by Erquint** [libsdl-org/sdlwiki#5]
![new page screenshot](https://i.imgur.com/OQUkCaZ.png)
Including `search`, `offline html` and other such.

**Comment by Erquint** [comment]
![header screenshot](https://i.imgur.com/JKPT91u.png)
The header is no better…

**Comment by icculus** [comment]
The header is just temporary text in the local copy, which I've now changed, and I made the footer text normal size in https://github.com/icculus/ghwikipp/commit/97de1560f5f14f926abc22c233680d9932fbcb70
