### ISSUE TITLE
[SDL3.1.1] - SDL_RenderGeometry Example failure

### ISSUE THREAD

**Issue by sechshelme** [libsdl-org/sdlwiki#504]
https://wiki.libsdl.org/SDL3/SDL_RenderGeometry

This example only seems to work with SDL2, even though it is on the SDL3 Wiki.
I removed the position in SDL_CreateWindow.
For SDL_CreateRenderer there is only SDL_RENDERER_PRESENTVSYNC as a flag.
After these changes the program runs, but the triangle remains white, it does not become colored.

Only this is SDL3 compliant.
```c
case SDL_EVENT_QUIT:
```

Tested on Linux 64Bit

**Comment by slouken** [comment]
I've updated the Wiki, thanks!
