### ISSUE TITLE
Feedback on page SDL2/SDL_TextInputEvent

### ISSUE THREAD

**Issue by Chwegrwn** [libsdl-org/sdlwiki#517]
Apology for an inaccuracy in my previous feedback. I see the type of SDL_TEXTINPUT member 'text' is given as char text [SDL_TEXTINPUTEVENT_TEXT_SIZE]. Type and value of SDL_TEXTINPUTEVENT_TEXT_SIZE not easily found though..

**Comment by icculus** [comment]
The remarks have an easily-clickable [SDL_TEXTINPUTEVENT_TEXT_SIZE](https://wiki.libsdl.org/SDL2/SDL_TEXTINPUTEVENT_TEXT_SIZE) link now, so we should be good to go here.
