### ISSUE TITLE
`SDL_GetPath` still has a wiki page, despite being renamed to `SDL_GetUserFolder`

### ISSUE THREAD

**Issue by Semphriss** [libsdl-org/sdlwiki#522]
[SDL_GetPath](https://wiki.libsdl.org/SDL3/SDL_GetPath) was renamed to [SDL_GetUserFolder](https://wiki.libsdl.org/SDL3/SDL_GetUserFolder); both currently have wiki pages, despite SDL_GetPath no longer existing.

Additionally, SDL_GetPath links to the [SDL_Folder](https://wiki.libsdl.org/SDL3/SDL_Folder) page, but SDL_GetUserFolder does not.

**Comment by slouken** [comment]
@icculus, shouldn't this have been taken care of in the documentation cleanup?
