### ISSUE TITLE
Wiki: Add header Inclusion graph

### ISSUE THREAD

**Issue by Sackzement** [libsdl-org/sdlwiki#531]
A wiki page with an overview of the header inclusions could be helpful.
To give you an idea, here is a screenshot of a graph I created a while ago.

![SDL Inclusion Graph](https://github.com/libsdl-org/sdlwiki/assets/840326/d1ab9ec5-de15-4a2a-8d3b-88b3d8396833)

in reference to libsdl-org/SDL#9440

**Comment by slouken** [comment]
In general we recommend just using:
`#include <SDL3/SDL.h>`

**Comment by Sackzement** [comment]
> In general we recommend just using:
`#include <SDL3/SDL.h>`

Is it just because it is easier?
I like to include only the headers which are used. It makes auto-completion more clear.
Am I missing something?

**Comment by slouken** [comment]
It's just because it's easier, and also because if you're using precompiled headers you want the same content in the precompiled header everywhere you use it.

**Comment by Sackzement** [comment]
Thanks for explaining!
Some day I'll have to switch to these fancy "new" features like precompiled headers and unity builds.
Maybe when I stop drinking coffee :)
