### ISSUE TITLE
Feedback on page SDL2/SDL_GLattr

### ISSUE THREAD

**Issue by DanielGibson** [libsdl-org/sdlwiki#544]
This page used to contain actual information, see https://web.archive.org/web/20210211172225/https://wiki.libsdl.org/SDL_GLattr?highlight=%28%5CbCategoryEnum%5Cb%29%7C%28CategoryVideo%29

**Comment by Dv-Senna** [comment]
I've added back the good old informations about SDL_GLattr in this commit https://github.com/libsdl-org/sdlwiki/commit/056a3d16e670d219699cda54d1897625577fc2f7

**Comment by icculus** [comment]
Hmm, this didn't bridge to the headers, gonna check that out real fast.

**Comment by icculus** [comment]
Okay, this upset wikiheaders, so I've formatted this info into the headers in the expected format in https://github.com/libsdl-org/SDL/commit/155c3bb0a33a842d23f3dafc9bf541f0973cd686, and this bridged back to the wiki in 0585b475466dbacf705f45d89cb619a40b41ab99.
