### ISSUE TITLE
Feedback on page SDL3/Tutorials/AudioStream: interleaving?

### ISSUE THREAD

**Issue by RenaKunisaki** [libsdl-org/sdlwiki#546]
I don't see anywhere that explains whether audio streams expect data that's interleaved (LRLRLR) or planar (LLLRRR).

**Comment by icculus** [comment]
It's interleaved. I'll update the page.

**Comment by Green-Sky** [comment]
would fix https://github.com/libsdl-org/SDL/issues/9638

**Comment by icculus** [comment]
This is fixed in https://github.com/libsdl-org/SDL/commit/d3a62d8298305a659592581eff481efcb37c5c53, which is now live on https://wiki.libsdl.org/SDL3/CategoryAudio
