### ISSUE TITLE
Feedback on page SDL3/SDL_PeepEvents

### ISSUE THREAD

**Issue by RenaKunisaki** [libsdl-org/sdlwiki#547]
The page doesn't say whether it's allowed to write something like `SDL_PeepEvents(NULL, 1000000, SDL_PeekEvent, SDL_EVENT_FIRST, SDL_EVENT_LAST);` to return the number of queued events without actually retrieving them. (ie is `events` allowed to be null?) 

If not, I'd like to suggest that; I don't see any way to get that information, which would be helpful for debugging.

**Comment by slouken** [comment]
Fixed, thanks!
