### ISSUE TITLE
Fill in missing pieces of SDL3/NewFeatures

### ISSUE THREAD

**Issue by icculus** [libsdl-org/sdlwiki#557]
I threw together a list of some obvious things by just looking at header filenames, but I'm sure there are things I missed.

https://wiki.libsdl.org/SDL3/NewFeatures

Things like the GPU API can get added when they land in revision control, and things that are changed-for-the-better but exist in SDL2 should be skipped. Notable new features added to existing SDL2 subsystems should be included.

Anything obvious missing from this list?

**Comment by slouken** [comment]
Did you look at WhatsNew.txt?

**Comment by icculus** [comment]
I did, and it turned out we basically made the same list.  :)

But now I'm digging into smaller things that aren't easily noticed in the function list (like the SDL_GetStringRule, or how the naming convention is consistent across the API), and the list on the wiki is getting pretty nice now!

I'm sure there's more I've missed that's worth mentioning, so I'll leave this open for now.

**Comment by icculus** [comment]
I think this is pretty solid, if we stay on top of it with new things going forward.
