### ISSUE TITLE
Feedback on page SDL2/SDL_BlitSurface - which pixel will be copied?

### ISSUE THREAD

**Issue by ekskirl** [libsdl-org/sdlwiki#576]
Hello,
until I got it work I was a little bit confused about the description: "if SDL_SRCCOLORKEY set, only copy the pixels matching the source color key" becaus in my understatement this says to me, that not the other pixel will be blitted.
Should it be: "if SDL_SRCCOLORKEY set, only copy the pixels **_don't_** matching the source color key"?
Gettings from Germany, Brandenburg, Velten
Ekkehard

**Comment by slouken** [comment]
Yep, that's totally wrong. Thanks for catching it!
