### ISSUE TITLE
Background may be too dark

### ISSUE THREAD

**Issue by Erquint** [libsdl-org/sdlwiki#6]
I prefer dark to bright but this is uncomfortably dark.
This depends a lot on people's display capabilities, such as the capacity for contrast and, of course, personal preference.
Options would be very welcome but you could go for a dim compromise rather than what would look to some, myself sadly included, as pitch-black void.

**Comment by icculus** [comment]
I agree, I'm going to lighten it slightly.

(the CSS actually makes the page goes dark when the browser reports itself in dark mode, fwiw, but tweaking this is still ongoing.)

**Comment by icculus** [comment]
Current:
![2021-03-30_18-39](https://user-images.githubusercontent.com/673562/113066047-d67c1280-9187-11eb-8aac-505546380f39.png)

Proposed:
![2021-03-30_18-42](https://user-images.githubusercontent.com/673562/113066062-df6ce400-9187-11eb-9986-2cc73c6bc604.png)

The proposed version matches the text/background colors for GitHub's new "dark dimmed" theme. Is that better?

**Comment by Erquint** [comment]
Much better indeed.
I was going to suggest taking a page from GH's theme.

**Comment by Erquint** [comment]
As for adapting to browser/OS color — I don't think those features are developed/integrated/supported enough yet to rely on.

**Comment by icculus** [comment]
> As for adapting to browser/OS color — I don't think those features are developed/integrated/supported enough yet to rely on.

They aren't; mostly it's only reliable on macOS and iOS at the moment, but the CSS defaults to light mode on things that don't understand the CSS magic.

We _could_ add an option to select a mode in the UI, but that's low priority for me atm.

**Comment by icculus** [comment]
Fixed in 35c7f5cc6a02b659231f4de75e91352f8f86d717

**Comment by Erquint** [comment]
Technically, I see this feature supported on both Windows and Android as well but I can also see how some discrepancies may arise, especially depending on user software choices.
