### ISSUE TITLE
Feedback on page SDL3/CategoryGPU

### ISSUE THREAD

**Issue by DanielGibson** [libsdl-org/sdlwiki#616]
> It is optimal for apps to pre-compile the shader formats they might use, but for ease of use SDL provides a [satellite single-header library](https://github.com/libsdl-org/SDL_gpu_shadercross) for performing runtime shader cross-compilation.

As far as I can tell that's not a single-header library at all: There's three headers in that repo, and it also seems to additionally depend on the [SPIRV-Cross](https://github.com/KhronosGroup/SPIRV-Cross) library and several d3d/dx libs, which are not single header or even header-only.

**Comment by slouken** [comment]
Thanks for the feedback!
