### ISSUE TITLE
Feedback on page SDL3/SDL_CopyFile

### ISSUE THREAD

**Issue by niconii** [libsdl-org/sdlwiki#623]
The documentation for `SDL_CopyFile` says this:

> if the calling thread terminates (or the power goes out) during the copy, `oldpath`'s previous contents will be gone, replaced with an incomplete copy of the data

But, is this right? In the first place, I don't see why it should be writing to `oldpath` at all, since it's the source, not the destination. Looking at the [POSIX](https://github.com/libsdl-org/SDL/blob/d9e6fe0b7a22dae7835c62a120f1a22585b0d9c0/src/filesystem/posix/SDL_sysfsops.c#L83-L136) and [Windows](https://github.com/libsdl-org/SDL/blob/d9e6fe0b7a22dae7835c62a120f1a22585b0d9c0/src/filesystem/windows/SDL_sysfsops.c#L141-L161) implementations seems to support this.

Maybe this should say `newpath` instead of `oldpath`?

**Comment by icculus** [comment]
Good catch, thanks!
