### ISSUE TITLE
Feedback on page SDL3/SDL_CreateMutex

### ISSUE THREAD

**Issue by owf684** [libsdl-org/sdlwiki#634]
When using clang++ I was not able to compile the following from your example

```cpp
SDL_Mutex *mutex ;
mutex = SDL_CreateMutex();
```
This was too ambiguous for the compiler. needed to define and declare all in one line

```cpp
SDL_Mutex *mutex = SDL_CreateMutex();
```

only happened when I tried this outside of main, so don't know if this is a real issue. Might just be my idiocy.

**Comment by icculus** [comment]
Outside of a C function, you can't have code (like the first case), only variable declarations that (in the second case) have an initializer.

**Comment by owf684** [comment]
Thanks Ryan. I knew I was dumb 👍🏼👍🏼👍🏼👍🏼

**Comment by icculus** [comment]
You aren't dumb, you just learned something new.  :)
