### ISSUE TITLE
CategoryAPI (API reference by Name) is borked.

### ISSUE THREAD

**Issue by Erquint** [libsdl-org/sdlwiki#7]
![footer screenshot](https://i.imgur.com/fqydcMX.png)
Tried downloading the "offline html" provided in the footer.
![borked CategoryAPI.html screenshot](https://i.imgur.com/SsptRL8.png)
Opened the `CategoryAPI.html` (API reference by Name) file and saw that 3 sections out of 4 are borked.

**Comment by Erquint** [comment]
Oy vey! That's doesn't just apply to the offline download…
The live version is just as borked.

**Comment by icculus** [comment]
yeah, this is leftover from MoinMoin, we just need to clean these out with basic page edits (or a clever perl script).

**Comment by weslord** [comment]
@icculus I'm willing to do some manual cleanup but want to confirm I've got the right plan, first, before generating dozens of potentially misguided PRs.

I was going to delete the MoinMoin tags and move the links under the correct headings (eg, structs under the Structures header, and so on), but it looks like `build_categories.php` will automatically add everything to the bottom again and we'd end up with redundant entries... so I might as well delete the category headers too while I'm at it, right?

**Comment by icculus** [comment]
So this all got a big upgrade this morning, so now the categories are automatically managed (and can still have custom text on the page above the category lists).

https://wiki.libsdl.org/SDL2/CategoryAPI
