### ISSUE TITLE
Feedback on page FrontPage: include vulkan and metal reference

### ISSUE THREAD

**Issue by markusheukelom** [libsdl-org/sdlwiki#70]
Hi,

“via OpenGL and Direct3D” is only mentioned, so I skipped sdl at first it thinking it doesnt support modern osx. I was wrong.

please mention Apple Metal and Vulkan and possibly other graphics technology. Also Ipad os?

**Comment by icculus** [comment]
Fixed, thanks!

(We mention iOS, which covers iPads, I think.)
