### ISSUE TITLE
Feedback on page Android

### ISSUE THREAD

**Issue by ZLTJohn** [libsdl-org/sdlwiki#71]
Bad formatting. It seems like markdown but it is really hard to understand. Some command are even wrong.
Here is part of it:

tar xf SDL2-2.0.5.tar.gz tar xf SDL2_image-2.0.1.tar.gz tar xf SDL2_mixer-2.0.1.tar.gz tar xf SDL2_net-2.0.1.tar.gz tar xf SDL2_ttf-2.0.14.tar.gz

ln -s SDL2-2.0.5 SDL2 ln -s SDL2_image-2.0.1 SDL2_image ln -s SDL2_mixer-2.0.1 SDL2_mixer ln -s SDL2_net-2.0.1 SDL2_net ln -s SDL2_ttf-2.0.14 SDL2_ttf ```

**Comment by icculus** [comment]
This got cleaned up awhile ago.
