### ISSUE TITLE
Feedback on page FAQDevelopment

### ISSUE THREAD

**Issue by AMDmi3** [libsdl-org/sdlwiki#79]
`Do I #include <SDL.h> or <SDL/SDL.h>?` [item](http://wiki.libsdl.org/FAQDevelopment#do_i_include_sdl.h_or_sdlsdl.h) seems to be broken, as the code example is not rendered (commented out in the source)

**Comment by icculus** [comment]
Fixed in https://github.com/libsdl-org/sdlwiki/commit/8995b1f2bdaa0ad1b81bd2349c7a97ab1ed9bb6c, thanks!
